### ISSUE TITLE
Unable to npm start due to errors

### ISSUE THREAD

**Issue by TroyWolf** [suvankar-kundu/node-express-es6-boilerplate#2]
Fresh clone and followed instructions. `npm build` followed by `npm start` results in:

```
twolf@sbridge:/tmp/node-express-es6-boilerplate$ npm run start

> node-express-es6-boilerplate@1.0.0 start /tmp/node-express-es6-boilerplate
> babel-node src/index.js

2020-02-01T16:21:40.792Z - info: Server started on port 5000
events.js:282
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '../logs/2020-02-01.application.log'
Emitted 'error' event on  instance at:
    at WriteStream.<anonymous> (/tmp/node-express-es6-boilerplate/node_modules/winston-daily-rotate-file/index.js:571:16)
    at WriteStream.emit (events.js:305:20)
    at WriteStream.EventEmitter.emit (domain.js:483:12)
    at internal/fs/streams.js:343:14
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../logs/2020-02-01.application.log'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-express-es6-boilerplate@1.0.0 start: `babel-node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-express-es6-boilerplate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/twolf/.npm/_logs/2020-02-01T16_21_40_809Z-debug.log
```

**Comment by Chakshu12345** [comment]
hey TroyWolf..I am facing same issue have u got any solution for this

**Comment by TroyWolf** [comment]
> hey TroyWolf..I am facing same issue have u got any solution for this

That was too long ago for me to remember. I think I just gave up on this lib and went a different direction since nobody chimed in with any answers. When I follow the README for a freshly cloned system and it will not start, I'm pretty quick to move on if I don't find a quick answer. I got things to do!

**Comment by Chakshu12345** [comment]
ok thanks
